rng('default');
dataRoot = '.';
images = imageDatastore(dataRoot, 'IncludeSubfolders', true, ...
                            'LabelSource', 'foldernames');
[train, val, test] = splitEachLabel(images, 0.7, 0.15, 0.15);

augmenter = imageDataAugmenter('RandRotation', [-20, 20], ...
                                 'RandXTranslation', [-4, 4], ...
                                 'RandYTranslation', [-4, 4], ...
                                 'RandXReflection', true, ...
                                 'RandXShear', [-3, 3], ...
                                 'RandXScale', [0.95, 1.05], ...
                                 'RandYScale', [0.95, 1.05]);

augmentedTrain = augmentedImageDatastore([48, 48, 1], train);

%% Make network
layers = makeSimpleNet([48, 48, 1], numel(unique(images.Labels)));

options = trainingOptions('sgdm', ...
                        'ExecutionEnvironment', 'cpu', ...
                        'MiniBatchSize', 32, ...
                        'MaxEpochs', 40, ...
                        'InitialLearnRate', 0.00156, ...
                        'L2Regularization', 0.0007, ...
                        'LearnRateSchedule', 'piecewise', ...
                        'LearnRateDropPeriod', 20, ...
                        'LearnRateDropFactor', 0.5, ...
                        'ValidationData', val, ...
                        'ValidationPatience', Inf, ...
                        'Verbose', true);
                   
diary('paper.txt')
net = trainNetwork(augmentedTrain, layers, options);
save('fer.mat', 'net');

options = trainingOptions('sgdm', ...
                        'ExecutionEnvironment', 'cpu', ...
                        'MiniBatchSize', 32, ...
                        'MaxEpochs', 60, ...
                        'InitialLearnRate', 0.000156, ...
                        'L2Regularization', 0.0007, ...
                        'ValidationData', val, ...
                        'ValidationPatience', Inf, ...
                        'Verbose', true);

net = trainNetwork(augmentedTrain, net.Layers, options);
save('fer2.mat', 'net');
diary off
